name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # Run WebdriverIO tests
      - name: Run WebdriverIO Tests
        run: npm run wdio

      # Install Allure Command-line tool globally
      - name: Install Allure Command-line
        run: npm install -g allure-commandline --save-dev

      # Verify Allure Installation
      - name: Verify Allure Installation
        run: allure --version

      # Ensure allure-results directory exists and is populated
      - name: List Allure Results
        run: ls -la ./allure-results || echo "No allure-results found"

      # Generate Allure Report (No Server Start)
      - name: Generate Allure Report
        run: npm run generateAllureReport || echo "Failed to generate Allure report"

      # Generate Allure Report as a single file (No opening in CI)
      - name: Generate Single-File Allure Report
        run: allure generate --single-file allure-results --clean -o ./allure-report

      # Ensure allure-report directory exists
      - name: Ensure Allure Report Directory Exists
        run: |
          mkdir -p allure-report
          ls -la allure-report || echo "No allure-report found"

      # Upload Allure Report as an Artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
