name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CI: true  # Setting the CI environment variable

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Firefox (if you're using Firefox for WebdriverIO tests)
      - name: Install Firefox
        run: sudo apt-get install -y firefox

      # Ensure the Firefox version (if you're using Firefox for WebdriverIO)
      - name: Check Firefox Version
        run: firefox --version

      # Optional: List node and npm versions for debugging
      - name: Check Node and NPM Versions
        run: |
          node -v
          npm -v

      # Run WebdriverIO tests
      - name: Run WebdriverIO Tests
        run: npm run wdio
        # Optional: Add debugging to see test results output
        continue-on-error: false  # If you want to stop the workflow if tests fail

      # Install Allure command-line tool
      - name: Install Allure Command-line
        run: npm install allure-commandline --save-dev

      # Ensure the allure-results directory exists
      - name: Ensure Allure Results Directory
        run: mkdir -p ./allure-results

      # Generate Allure report
      - name: Generate Allure Report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      # Upload the Allure results (raw data) as an artifact
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      # Upload the generated Allure report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      # Optional: Debugging step to list files in the project directory
      - name: List Files in Current Directory
        run: ls -al
