name: Deploy Allure Report to GitHub Pages

on:
  push:
    branches:
      - main  # Specify the branches you want to trigger on for pushes
  pull_request:
    branches:
      - main  # Specify the branches you want to trigger on for pull requests

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Generate Allure Report
      run: npx allure generate ./allure-results --clean

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report  # Change this if your report path is different
